### ISSUE TITLE
issues with DotDictionary

### ISSUE THREAD

**Issue by Vafa-Andalibi** [cloudmesh-community/cm#34]
The DotDictionary seems to be pretty unstable. I have been dealing with some strange issues (for several hours) in Config() and after tracing the debug route, turns out the issue is with DotDictionary. 
Here's some issues that I've been dealing with while developing the new module:
- integer keys produce problems: 
```python
q = DotDictionary({'a':{2:2},'3':4})
type(q.get('a.2'))
<class 'NoneType'>
```
similarly: 
```python
>>> q = DotDictionary({2:{3:2},'3':4})
>>> q.get(2)
Traceback (most recent call last):
  File "/snap/pycharm-professional/89/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/corriel/gitrepos/courses/e516_CloudComputing_cloudmesh/cm4/configuration/dot_dictionary.py", line 33, in get
    return self.__getitem__(key, default)
  File "/home/corriel/gitrepos/courses/e516_CloudComputing_cloudmesh/cm4/configuration/dot_dictionary.py", line 29, in __getitem__
    val = self._deep_get(self, key.split("."), default)
AttributeError: 'int' object has no attribute 'split'
>>> type(q.get('2'))
<class 'NoneType'>
```

Most important of all, DotDictionary cannot be updated and does not even raise an error which makes it very difficult to trace back and debud (this updating is quite crucial for config management) : 
```python 
>>> q = DotDictionary({'a':{'b':'c'},'d':'e'})
>>> q.get('a')
DotDictionary({'b': 'c'})
>>> q.get('a.b')
'c'
>>> q.get('a').update({'n':'m'})
>>> q
DotDictionary({'a': {'b': 'c'}, 'd': 'e'})
```
As you can see the update is not reflected in the dictionary. This gets even worse when the regular indexing of dictionary doesn't update it either: 
```python
>>> q['a']
DotDictionary({'b': 'c'})
>>> q['a'].update({'n':'m'})
>>> q
DotDictionary({'a': {'b': 'c'}, 'd': 'e'})
```
This can raise strange and unexpected issues and behaviors (hard to debug) in cloudmesh and should be fixed asap.

**Comment by davidmdem** [comment]
That `DotDictionary` implementation was meant as helper class to be used via a Config. Simple scalar `get` and `set` operations via the Config are the only thing that have been used or [tested](https://github.com/cloudmesh-community/cm/blob/master/test/test_config.py) so far.

Get a value
```
self.defaults = config.get('cloud.azure.default')
id = defaults["MY_DEFAULT_ID"]
```

Set a value
```
_config.set("my.nested.value") = "some value"
```

With that said, this was implemented before [`cloudmesh.common`](https://github.com/cloudmesh/cloudmesh.common) was available to the project as of last week and I'm not sure that it's worth keeping around.

This is something that will warrant might warrant its own issue, but we're starting to get a lot of different config handling implementations and I wonder if it is feasible for everyone to consolidate around the [`ConfigDict`](https://github.com/cloudmesh/cloudmesh.common/blob/master/cloudmesh/common/ConfigDict.py) class found in cloudmesh.common.

**Comment by davidmdem** [comment]
@swsachith Tagging you for the `Config`/[`ConfigDict`](https://github.com/cloudmesh/cloudmesh.common/blob/master/cloudmesh/common/ConfigDict.py) considerations.

**Comment by laszewsk** [comment]
I think this is just such a small part, of it, that if it works its ok, if not just use dict ...

I would make a comment in dotcict.

in my case I did a 3 line dotdict that only was interested in getting the top most elements as that is what i needed for docopts. that is mostly the only place i used this
